### ISSUE TITLE
[Android]Transaction details is not updated after confirmation is submitted( spinner is never disappeared)

### ISSUE THREAD

**Issue by liliya-soroka** [gnosis/safe-android#1284]
**Describe the bug**
Transaction details is not updated after confirmation is submitted, instead of it the loading icon is displayed for a very long time.

**To Reproduce**
1. Add an owner key to the safe
2. Create a tx that will require confirmation of the owner
3. Go to the transaction details and click Confirm button
Current result: Snackbar is displayed with a success message, but the spinner doesn't disappear and the status is not updated from "Awaiting your confirmation" to "Awaiting confirmation" 

**Expected behavior**
The state should be updated after the tx is successfully confirmed

**Screenshots**
![image.png](https://images.zenhubusercontent.com/5ed757c29459bb36bacd4bba/b6163431-81e0-44a8-b311-11e849fe6308)

**Smartphone (please complete the following information):**
 - Device: Huawei P30
 - Android Version: 10
 - App Version 2.10.0 -2063rc
safe = 0x8675B754342754A30A2AeF474D114d8460bca19b

**Environment**
prod mainnet 
**Additional context**

**Comment by tschubotz** [comment]
hmm, I'm torn about the severity level of this bug. For me it's `major` or `critical`.

`major` because the signing still works. Users have to just to back once.
However I tend to `critical` since signing onmobile is something that we want users to get to do. So it's not great for trusting the mobile app if on the tx details, even a manual reload doesn't work. I would like to fix this for 2.10.0 to be honest.

**Comment by liliya-soroka** [comment]
Verified
app version 2.10.0 -2098rc
