### ISSUE TITLE
Adjust push notification navigation & show network data

### ISSUE THREAD

**Issue by elgatovital** [gnosis/safe-android#1565]
- [x] Use chainId from push notification for active safe selection
- [x] Show chain data in notification

- [x] Add chain name to the title:
```
Incoming transfer -> Incoming transfer (Mainnet)
Transaction successful -> Transaction successful (Mainnet)
....
```
see discussion here https://gnosisinc.slack.com/archives/CQB729LLF/p1626098150123500
original push notifications ticket: https://github.com/gnosis/safe/issues/290

- [x] Adjust notifications for native coin transfers:
```
Incoming  <token symbol> (<network name>)
<safe name>: <amout> <token symbol> received
```
where amount is formatted using chain's native currency data

**Comment by liliya-soroka** [comment]
no notification in staging mainnet app if the notification for the rinkeby safe should be received

app version 2.18.0 -2977

steps:
1. add safe liltestsafe.eth on rinkeby in staging mainnet app
2. close app and send eth/erc20 to the safe from step 1

Current result: notification for the staging rinkeby app appears instead of staging mainnet app(multinetwork app)
