### ISSUE TITLE
Fingerprint sensor can't be enabled

### ISSUE THREAD

**Issue by tschubotz** [gnosis/safe-android#249]
**Describe the bug**
I used to be able to enable the fingerprint for signing transactions and unlocking the app. Now not anymore. 

**To Reproduce**
*In onboarding*
1. Clean install
2. Setup pw
3. I end up inside the Safe, but expected to get asked if I want to enable fingerprint

*In Settings*
1. I have a app (no Safe created yet)
2. I open settings
3. I see that fingerprint is disabled
4. Nothing happens when tapping the toggle.

**Expected behavior**
I expect to be able to use the fingerprint sensor

**Screenshots**
-

**Smartphone (please complete the following information):**
 - Device: Gnosis MotoG
 - Android Version: 7.1.1
 - App Version: 0.7.0-internal

**Additional context**
-

**Comment by rmeissner** [comment]
Seems this might be related to https://github.com/gnosis/safe-android/commit/919fd4b19365da0c12f35dd070369b223309e427#diff-c8cc2dd42271f2bf39c6aa81eb6a5529L7

**Comment by fmrsabino** [comment]
I'm going to revert this change.

`android.permission.USE_BIOMETRIC"` requires the `BiometricPrompt` which is part of `androidx.biometric:biometric`

This requires some bigger changes including UI/UX changes that need to be discussed since with the new version [we have a unified interface for user authentication](https://developer.android.com/about/versions/pie/android-9.0) (Unified biometric authentication dialog).
