### ISSUE TITLE
Gnosis Safe on phones without Google Play Account

### ISSUE THREAD

**Issue by beralt85** [gnosis/safe-android#385]
### Expected behavior
I can use Gnosis Safe on my Google-free phone without a Google account.
Better even, I can install and use it from an open repo like F-Droid, without using the need for a google Account.

### Actual behavior
When downloading the apk via a access to google play via an anonymous/multiple people account, signing notifications are not received by the phone.

### Steps to reproduce the behavior
Try to authorize any transaction on a phone where you obtained the apk for instance using the aurora or yalp third party stores accessing google play.

### Additional information

- Device: Shift Phone 6m
- Android OS version: Lineage 15.1 (unofficial), Android 8.1.0
- Safe app version: 1.4.1

**Comment by rmeissner** [comment]
Hey @beralt85 we are aware of this dependency and are working on providing alternative means.

The current features that are in progress to improve this are WalletConnect support and hardware wallet support (where the hardware wallet is directly connected to the phone).

This would still not allow to use the setup with the Safe extension, since that one is based on push notifications (also the reason why it won't work with Brave). This might be refactored in the future. 

Sending funds with a Safe that doesn't have 2fa enabled should still work, or do you get an error in that case?

**Comment by teohhanhui** [comment]
It'd still be great to have this app published on F-Droid.

**Comment by rmeissner** [comment]
All apks can be downloaded in this repository as they are attached to the releases.

**Comment by 48-mq** [comment]
@DmitryBespalov 

I urge you to reconsider your stance on adding the project to a public open-source repository like F-Droid. Given the GPL license, such a move would serve many purposes:

1. Make your software more easily accessible and updated by those who don't use Play Services - including those who don't trust it for critical/sensitive software.
2. Open up the app to better review and scrutiny from new sections of the open source community. Sunlight is the best disinfectant!
3. Further enhance the trust you've built over the years.
4. Invite new contributors to your project.

**Comment by 48-mq** [comment]
@DmitryBespalov Any thoughts on tackling this?
