### ISSUE TITLE
Stepper should not be shown in 2fa intro screens

### ISSUE THREAD

**Issue by rmeissner** [gnosis/safe-android#502]
Currently we show the stepper (with the 3 steps) in the intro screens for KeyCard and the Extension. According to designs this should not be the case.

Extension: https://zpl.io/a7e0k5E
KeyCard: https://zpl.io/b6B0OmK

**Comment by elgatovital** [comment]
stepper is shown only during onboarding flow, when creating a new safe

**Comment by rmeissner** [comment]
But even when creating a Safe it should not be shown on these screens

**Comment by elgatovital** [comment]
https://zpl.io/2jWxzzr

**Comment by rmeissner** [comment]
That is a different screen (see the screens I linked)

**Comment by elgatovital** [comment]
ahh.... got it

**Comment by elgatovital** [comment]
but we have https://zpl.io/b6xPAmK - stepper is visible after pairing is done, but not before. It is a little bit inconsistent. What do you think?

**Comment by rmeissner** [comment]
For me the setup of the 2fa device is leaving the linear creation flow (intro creation -> intro 2fa -> intro phrase) and at that point you return to it. The current one feels weird to me, not sure about the other since I didn't see it on the device. But that is something you could probably check with @posthnikova 🙂

**Comment by posthnikova** [comment]
@elgatovital @rmeissner We don't show stepper here (https://zpl.io/a7e0k5E, https://zpl.io/b6B0OmK) because we don't need to show stepper on every screen inside the flow, only on start and end. On the devices list we don't show stepper and showing it on the next screen (Pair your Status Keycard) would be weird. Plus "Pair your Status Keycard" is a part of some other flows (Replace 2FA, Enable 2FA, Recover) and I wanted to avoid two versions of the same flow (with and without stepper).
