### ISSUE TITLE
View transaction list (#567)

### ISSUE THREAD

**Issue by elgatovital** [gnosis/safe-android#567]
Current tasks

- create tx repository
- query tx data from tx service
- use pagination
- show list

Transaction list:
User sees 2 sections:
A section for txs waiting for confirmations
Another section for txs that have been executed or cancelled
User sees all txs sorted in both sections:
Waiting for confirmations
Sorted by nonce, ascending
If 2 txs with same nonce, then put the one with the later creation date higher
Executed and cancelled
Executed txs sorted by execution date, descending (Both incoming and outgoing)
Add cancelled txs in that list with their created timestamp
Find more on the sorting in this doc.
User sees all incoming and outgoing transactions.
User can explore transaction details further by tapping on a transaction.
Transactions should be identifed by their nonce. There should not be another identifier.

**Comment by elgatovital** [comment]
screen: https://zpl.io/bzZ8zz8 (iOS)
TransactionListFragment with recycler view
pagination?  if yes check android pagination library or other 3rd party solutions

**Comment by biafra23** [comment]
Are we going to do pagination?

**Comment by rmeissner** [comment]
Yes there will be pagination, all our list endpoints have pagination (at least if it foreseeable that the number of items only increases over time)

**Comment by jpalvarezl** [comment]
The endpoint for transactions is located here:

https://safe-transaction.mainnet.staging.gnosisdev.com/api/v1/safes/<safe-address>/all-transactions/

**Comment by jpalvarezl** [comment]
Transaction type heuristic:

- Settings change -> transaction.to  and safe addresses are identical
- Transfer -> transaction.data  starts with 0xa9059cbb
- Custom transaction -> The rest

`Transfers` within a `Transaction` will contain the following class instead of `tokenAddress`

https://github.com/gnosis/safe-transaction-service/issues/96

`/safes/{address}/all-transactions` returns only `history` section of the whole list ( `nonce < currentSafeNonce`)

`/safes/{address}/transactions` returns only `queued` section of the whole list (`nonce > currentSafeNonce`)

Tx Sorting: https://github.com/gnosis/safe/wiki/How-should-transactions-be-sorted

Tx States: https://github.com/gnosis/safe/wiki/Safe-transaction-states
