### ISSUE TITLE
Upgrade to OkHttp 4 (LS: full regression)

### ISSUE THREAD

**Issue by elgatovital** [gnosis/safe-android#602]
see https://square.github.io/okhttp/upgrading_to_okhttp_4/
https://github.com/square/okhttp

**Comment by liliya-soroka** [comment]
@biafra23 , are the change influence on the whole app or just on some specific places/functions?

**Comment by biafra23** [comment]
@liliya-soroka Since we're using okhttp everywhere (where we do network call) it could have an impact anywhere. But it is unlikely that anything was broken. We have been using it for a while. It's tough to QA. If I would have to do it, I'd probably look into redirects (do we have any?) and correct return of error codes.

**Comment by liliya-soroka** [comment]
Verified
app version 2.5.0 -1421rc
