### ISSUE TITLE
Tx List: Create Tx Repository

### ISSUE THREAD

**Issue by elgatovital** [gnosis/safe-android#622]
Transaction network access needs to be defined according to https://github.com/gnosis/safe/issues/324

Added network access to the `all-transactions` endpoint.

Define the types like in the issue mentioned above.

Define unit tests for deserialisers using polymorphism. Unknown new types should be filtered the item out instead of throwing and crashing.

Map the 3 backend types (to this date) Multisig, Module, Ethereum transactions into Transfer, Settings change and Custom transactions. Provide unit tests asserting which fields from the DTOs map to the domain classes.

**Comment by jpalvarezl** [comment]
Transaction type heuristic:

- Settings change -> transaction.to  and safe addresses are identical
- Transfer -> transaction.data  starts with 0xa9059cbb
- Custom transaction -> The rest

`Transfers` within a `Transaction` will contain the following class instead of `tokenAddress`

https://github.com/gnosis/safe-transaction-service/issues/96

`/safes/{address}/all-transactions` returns only `history` section of the whole list ( `nonce < currentSafeNonce`)

`/safes/{address}/transactions` returns only `queued` section of the whole list (`nonce > currentSafeNonce`)

Tx Sorting: https://github.com/gnosis/safe/wiki/How-should-transactions-be-sorted

Tx States: https://github.com/gnosis/safe/wiki/Safe-transaction-states

**Comment by jpalvarezl** [comment]
https://github.com/gnosis/safe-transaction-service/issues/97

**Comment by biafra23** [comment]
Please see: https://github.com/gnosis/safe/wiki/How-do-we-determine-the-tx-type for help on how to distinguish between the tx types.

**Comment by jpalvarezl** [comment]
Looking good! Nice foundation!
