### ISSUE TITLE
Tx List: Fix retry logic

### ISSUE THREAD

**Issue by elgatovital** [gnosis/safe-android#623]
Retry doesn't work on Transactions list :
1. Open transactions list
2. Turn internet connection off
3. Scroll down
4. click retry : Nothing happened
5. Turn internet connection on
6. Click retry
Current result: Nothing happens

app version 1.12.1-54

Is error handling and no internet connection handling part of the task?

**Comment by jpalvarezl** [comment]
Transaction type heuristic:

- Settings change -> transaction.to  and safe addresses are identical
- Transfer -> transaction.data  starts with 0xa9059cbb
- Custom transaction -> The rest

`Transfers` within a `Transaction` will contain the following class instead of `tokenAddress`

https://github.com/gnosis/safe-transaction-service/issues/96

`/safes/{address}/all-transactions` returns only `history` section of the whole list ( `nonce < currentSafeNonce`)

`/safes/{address}/transactions` returns only `queued` section of the whole list (`nonce > currentSafeNonce`)

Tx Sorting: https://github.com/gnosis/safe/wiki/How-should-transactions-be-sorted

Tx States: https://github.com/gnosis/safe/wiki/Safe-transaction-states

**Comment by liliya-soroka** [comment]
reopened:
Retry doesn't work on Transactions list :
1. Open transactions list
2. Turn internet connection off
3. Scroll down
4. click retry : Nothing happened
5. Turn internet connection on
6. Click retry
Current result: Nothing happens

app version 1.12.1-54

Is error handling and no internet connection handling part of the task?

**Comment by tschubotz** [comment]
@elgatovital @jpalvarezl 

I assume that a fresh app start or switching tabs result in properly loading the tx list? Then I think this is `minor` right now.

**Comment by liliya-soroka** [comment]
Verified
app version 1.12.1 - 114 - No retry link any more in the message
