### ISSUE TITLE
Transaction List pagination

### ISSUE THREAD

**Issue by jpalvarezl** [gnosis/safe-android#662]
**Describe the solution you'd like**
The `all-transactions` endpoint returns items in pages that look like:

```kotlin
data class Page<T>(
    val count: Int,
    val next: String?,
    val previous: String?,
    val results: List<T>
)
```

We need to implement pagination so that we use the `next` link, if available to load more items in the list. Do not attempt setting `offset` or `limit` despite what the URL for `next` and `previous` may look like.

On the first page of data we should also fetch the `Safe` from the `/safes/{address}/` endpoint.

This is required so that we have the safe `nonce` and we can thus calculate the corresponding status of any given transactions. 

**Additional context**
Be reminded that the `TransactionRepository` expands each page of data, depending on whether or not many `transfers` are part of the response object.

**Comment by elgatovital** [comment]
PageKeyedDataSource -> PagedList<Transaction>

Adjust adapter to work with PagedList (instead of List)
Make data source part of the view model? Try not to polute repository with ui stuff.
PagingDataAdapter (RecyclerView subclass)

Testing (view model: loading next page, loading previous page, ui updates)
