### ISSUE TITLE
NFT details (action part for NFT's)

### ISSUE THREAD

**Issue by jpalvarezl** [gnosis/safe-android#792]
Design:https://zpl.io/VDyzLp3 & https://zpl.io/bLMwYBD

![image](https://user-images.githubusercontent.com/246473/92596070-800bbd00-f2a5-11ea-8c54-a3d48be0a089.png)

**Comment by biafra23** [comment]
@jpalvarezl Does the client gateway send the token description in the tx list?

**Comment by jpalvarezl** [comment]
There is not going to be a client gateway endpoint for this, at least not in the foreseeable future. The only logic that the clients should implement is to aggregate by `tokenAddress` and sort alphabetically by `tokenName`, as far as I understood. It was deemed in the refinement meeting that this was not a priority to push to the gateway for now.

**Comment by liliya-soroka** [comment]
Reopened:
The item details should be instead of group details on the tx details page
Current result: ![image.png](https://images.zenhubusercontent.com/5ed757c29459bb36bacd4bba/0b660ea2-9fb3-4311-8fba-de5421715d3f)
Expected result: https://app.zeplin.io/project/5e9efc30726e106958cc43de/screen/5ee8ddc8e175644aa196ad65
safe : 0x1230B3d59858296A31053C1b8562Ecf89A2f888b
tx nonce : 234

**Comment by biafra23** [comment]
>  The item details should be instead of group details on the tx details page

I don't understand, what you mean by that.

**Comment by tschubotz** [comment]
Let's remove "NFT action" from the requirements https://gnosisinc.slack.com/archives/C63LQTGNB/p1600077831459800?thread_ts=1600072639.442800&cid=C63LQTGNB

**Comment by liliya-soroka** [comment]
Verified
app version 2.2.0 -1174rc
