### ISSUE TITLE
Undefined ERC721 tx: incoming doesn't have any symbol ( even NFT) + outgoing tx is defined as custom

### ISSUE THREAD

**Issue by liliya-soroka** [gnosis/safe-android#800]
**Describe the bug**
Some of the ERC721 tx doesn't have any symbol ( even NFT), just 1 is displayed.
It was expected that such cases will be handled by the client( not client gateway)

**To Reproduce**
1. Add safe 0x1230B3d59858296A31053C1b8562Ecf89A2f888b ( liltestsafe.eth)
2. Check the tx with nonce 

**Expected behavior**
If the symbol is not defined NFT should be used as symbol for ERC721

**Screenshots**
![image.png](https://images.zenhubusercontent.com/5ed757c29459bb36bacd4bba/dc8684f4-5f13-414c-ab04-e4807125e7ad)

**Smartphone (please complete the following information):**
 - Device: Pixel 4
 - Android Version: 10
 - App Version 1.12.1-86

**Additional context**

**Comment by jpalvarezl** [comment]
@Uxio0 How are transfers classified in the transaction service? Because it seems that the method matches the signature of a transfer for Erc721 but the contract might not really be one. 

Link from @rmeissner for your reference: https://rinkeby.etherscan.io/tx/0x1c7f031b2ffd6761bf7e56ff2e6334e3d74d5efba2de41b2fc74afdb178ddcdf#eventlog

**Comment by Uxio0** [comment]
> @Uxio0 How are transfers classified in the transaction service? Because it seems that the method matches the signature of a transfer for Erc721 but the contract might not really be one.

@jpalvarezl Classification is done here https://github.com/gnosis/gnosis-py/blob/2487043fe5e040959bcde2042f3203fc07c909a5/gnosis/eth/ethereum_client.py#L310 . `Transfer` event has the same signature, but usually for ERC721 `tokenId` is `indexed` but for ERC20 `value` is never indexed, so log `data` should be empty for ERC721. That's the way I use to detect that, but of course it can fail (some contracts are not even indexing anything)

**Comment by rmeissner** [comment]
Ahh interesting, thanks for clarifying @Uxio0  ... yes this is something we could take into consideration on the gateway. I would say this is not something we will fix now but something we should keep track of for the future @jpalvarezl

**Comment by liliya-soroka** [comment]
Example:
Outgoing tx :
safe 0x938bae50a210b80EA233112800Cd5Bc2e7644300
nonce 62

Incoming tx
safe 0x1230B3d59858296A31053C1b8562Ecf89A2f888b
date aug 24  13:34 (Berlin time)

**Comment by liliya-soroka** [comment]
@rimeissner, @Uxio0  . I just afraid of the most of the ERTH721 tokens transactions in prod will have this issue ( even Criptokitty): outgoing tx as custom, incoming with +1 without any symbol. For me during testing beta release candidate even Criptokitty was defined as NFT ( don’t know if it was the same on back-end side)

**Comment by rmeissner** [comment]
We have the info for crypto kitties on mainnet: https://safe-transaction.gnosis.io/api/v1/tokens/0x06012c8cf97BEaD5deAe237070F9587f8E7A266d/ (or https://safe-transaction.mainnet.staging.gnosisdev.com/api/v1/tokens/0x06012c8cf97BEaD5deAe237070F9587f8E7A266d/ for staging) so that should not be the case ... if this doesn't show up on mainnet then this would be a bug. For me this is not a critical bug ... tokens without information are not that commonly used, and at some point we should be able to manually add tokens (similar to the relay service) so that we have a complete database ... anyways for me this is a minor bug (cc @tschubotz )

**Comment by biafra23** [comment]
Is this something the App can fix? This seems to be a backend issue. Can I assign this ticket to @jpalvarezl ?

**Comment by jpalvarezl** [comment]
The gateway always requests the `TokenInfo` for transfers, if they originate from a MultiSigTx or an object in Transfers. I don't think this is a backend issue, but to be able to fully discard this possibility, it would be nice to have a clearer way to find this transaction. 

If the transaction in question in this issue is `ethereum_0x1230B3d59858296A31053C1b8562Ecf89A2f888b_0x1c7f031b2ffd6761bf7e56ff2e6334e3d74d5efba2de41b2fc74afdb178ddcdf_0xc8266fa354d264e8` (gateway id) then the token address in question is `0xe6971941162b1D4d2ab4D47eDc1CB3b2E1743941` which returns `Not found` in the safe transaction service. There is nothing we can do in this situation at a gateway level as the `token_info` is just unavailable. At least to the best of my understanding.

**Comment by Uxio0** [comment]
> If the transaction in question in this issue is `ethereum_0x1230B3d59858296A31053C1b8562Ecf89A2f888b_0x1c7f031b2ffd6761bf7e56ff2e6334e3d74d5efba2de41b2fc74afdb178ddcdf_0xc8266fa354d264e8` (gateway id) then the token address in question is `0xe6971941162b1D4d2ab4D47eDc1CB3b2E1743941` which returns `Not found` in the safe transaction service. There is nothing we can do in this situation at a gateway level as the `token_info` is just unavailable. At least to the best of my understanding.

I understand we are talking about Rinkeby, the contract is not verified and I don't know what it is, so we cannot get information on that "token".

**Comment by liliya-soroka** [comment]
Verified
app version 2.2.0 - 1174rc
